import type {
  Client, Campaign, Asset, AIAction, TeamMember, DashboardMetrics, ChartDataPoint,
} from "@/types";

export const MOCK_CLIENTS: Client[] = [
  {
    id: "client-1",
    agency_id: "agency-1",
    name: "Nike Sports",
    logo_url: "https://picsum.photos/seed/nike/40/40",
    industry: "Sportswear & Footwear",
    website: "nike.com",
    meta_connected: true,
    google_connected: true,
    shopify_connected: true,
    shopify_store_url: "nike-sports.myshopify.com",
    monthly_budget: 85000,
    currency: "USD",
    goal: {
      target_roas: 5.0,
      target_revenue: 425000,
      target_cpa: 8,
      monthly_budget: 85000,
      timeframe_start: "2026-05-01",
      timeframe_end: "2026-05-31",
      notes: "Peak summer season — push ROAS above 5x before June discount events.",
    },
    created_at: "2024-01-15T00:00:00Z",
    campaign_count: 12,
    active_campaigns: 8,
    total_spend: 62400,
    roas: 4.2,
    shopify_revenue: 284600,
  },
  {
    id: "client-2",
    agency_id: "agency-1",
    name: "TechVault",
    logo_url: "https://picsum.photos/seed/tech/40/40",
    industry: "B2B SaaS",
    website: "techvault.io",
    meta_connected: true,
    google_connected: true,
    shopify_connected: false,
    monthly_budget: 45000,
    currency: "USD",
    goal: {
      target_cpa: 90,
      target_revenue: 140000,
      monthly_budget: 45000,
      timeframe_start: "2026-05-01",
      timeframe_end: "2026-07-31",
      notes: "Q2 pipeline push — prioritize demo signups over brand awareness.",
    },
    created_at: "2024-02-20T00:00:00Z",
    campaign_count: 7,
    active_campaigns: 5,
    total_spend: 38200,
    roas: 3.1,
  },
  {
    id: "client-3",
    agency_id: "agency-1",
    name: "FreshBrew Coffee",
    logo_url: "https://picsum.photos/seed/coffee/40/40",
    industry: "Food & Beverage",
    website: "freshbrew.com",
    meta_connected: true,
    google_connected: false,
    shopify_connected: true,
    shopify_store_url: "freshbrew-coffee.myshopify.com",
    monthly_budget: 18000,
    currency: "USD",
    goal: {
      target_roas: 6.5,
      target_revenue: 117000,
      monthly_budget: 18000,
      timeframe_start: "2026-05-01",
      timeframe_end: "2026-05-31",
    },
    created_at: "2024-03-10T00:00:00Z",
    campaign_count: 4,
    active_campaigns: 3,
    total_spend: 14600,
    roas: 5.8,
    shopify_revenue: 96200,
  },
  {
    id: "client-4",
    agency_id: "agency-1",
    name: "LuxeHome Decor",
    logo_url: "https://picsum.photos/seed/home/40/40",
    industry: "Home & Lifestyle",
    website: "luxehome.co",
    meta_connected: false,
    google_connected: true,
    shopify_connected: true,
    shopify_store_url: "luxehome-decor.myshopify.com",
    monthly_budget: 32000,
    currency: "USD",
    goal: {
      target_roas: 4.0,
      target_revenue: 128000,
      target_cpa: 18,
      monthly_budget: 32000,
      timeframe_start: "2026-05-01",
      timeframe_end: "2026-06-30",
    },
    created_at: "2024-04-05T00:00:00Z",
    campaign_count: 6,
    active_campaigns: 4,
    total_spend: 24100,
    roas: 3.7,
    shopify_revenue: 89200,
  },
];

export const MOCK_CAMPAIGNS: Campaign[] = [
  {
    id: "camp-1",
    client_id: "client-1",
    platform: "meta",
    platform_campaign_id: "23855501234",
    name: "Summer Collection - Awareness",
    objective: "awareness",
    status: "active",
    daily_budget: 1200,
    currency: "USD",
    start_date: "2024-06-01",
    targets: { roas: 4.0, monthly_budget: 36000 },
    metrics: {
      spend: 28400, impressions: 4200000, clicks: 126000, ctr: 3.0,
      cpc: 0.23, cpm: 6.76, conversions: 3840, conversion_rate: 3.05,
      roas: 4.6, cpa: 7.40, reach: 1800000, frequency: 2.3,
      updated_at: new Date().toISOString(),
    },
    ai_managed: true,
    optimization_frequency: "1hour",
    created_at: "2024-06-01T00:00:00Z",
    updated_at: new Date().toISOString(),
  },
  {
    id: "camp-2",
    client_id: "client-1",
    platform: "google",
    platform_campaign_id: "98712345",
    name: "Running Shoes - Performance Max",
    objective: "performance_max",
    status: "active",
    daily_budget: 800,
    currency: "USD",
    start_date: "2024-05-15",
    targets: { roas: 5.0, cpa: 12, monthly_budget: 24000 },
    metrics: {
      spend: 18200, impressions: 2100000, clicks: 84000, ctr: 4.0,
      cpc: 0.22, cpm: 8.67, conversions: 1820, conversion_rate: 2.17,
      roas: 5.2, cpa: 10.0,
      updated_at: new Date().toISOString(),
    },
    ai_managed: true,
    optimization_frequency: "30min",
    created_at: "2024-05-15T00:00:00Z",
    updated_at: new Date().toISOString(),
  },
  {
    id: "camp-3",
    client_id: "client-1",
    platform: "google",
    platform_campaign_id: "98712346",
    name: "Brand Search - Core Terms",
    objective: "search",
    status: "active",
    daily_budget: 400,
    currency: "USD",
    start_date: "2024-04-01",
    targets: { cpa: 8, monthly_budget: 12000 },
    metrics: {
      spend: 9800, impressions: 320000, clicks: 44800, ctr: 14.0,
      cpc: 0.22, cpm: 30.6, conversions: 1344, conversion_rate: 3.0,
      roas: 6.1, cpa: 7.3,
      updated_at: new Date().toISOString(),
    },
    ai_managed: true,
    optimization_frequency: "6hours",
    created_at: "2024-04-01T00:00:00Z",
    updated_at: new Date().toISOString(),
  },
  {
    id: "camp-4",
    client_id: "client-1",
    platform: "meta",
    platform_campaign_id: "23855501235",
    name: "Retargeting - Cart Abandoners",
    objective: "sales",
    status: "active",
    daily_budget: 500,
    currency: "USD",
    start_date: "2024-06-15",
    targets: { roas: 8.0, cpa: 5 },
    metrics: {
      spend: 4200, impressions: 840000, clicks: 25200, ctr: 3.0,
      cpc: 0.17, cpm: 5.0, conversions: 1260, conversion_rate: 5.0,
      roas: 9.2, cpa: 3.3, reach: 420000, frequency: 2.0,
      updated_at: new Date().toISOString(),
    },
    ai_managed: true,
    optimization_frequency: "15min",
    created_at: "2024-06-15T00:00:00Z",
    updated_at: new Date().toISOString(),
  },
  {
    id: "camp-5",
    client_id: "client-1",
    platform: "meta",
    platform_campaign_id: "23855501236",
    name: "Lookalike - High Value Customers",
    objective: "sales",
    status: "paused",
    daily_budget: 600,
    currency: "USD",
    start_date: "2024-07-01",
    targets: { roas: 3.5, cpa: 15 },
    metrics: {
      spend: 1800, impressions: 540000, clicks: 10800, ctr: 2.0,
      cpc: 0.17, cpm: 3.3, conversions: 162, conversion_rate: 1.5,
      roas: 2.1, cpa: 11.1, reach: 480000, frequency: 1.1,
      updated_at: new Date().toISOString(),
    },
    ai_managed: true,
    optimization_frequency: "daily",
    created_at: "2024-07-01T00:00:00Z",
    updated_at: new Date().toISOString(),
  },
  {
    id: "camp-6",
    client_id: "client-2",
    platform: "google",
    platform_campaign_id: "78945612",
    name: "Enterprise SaaS - Search",
    objective: "leads",
    status: "active",
    daily_budget: 900,
    currency: "USD",
    start_date: "2024-03-01",
    targets: { cpa: 120, conversions: 50 },
    metrics: {
      spend: 22400, impressions: 180000, clicks: 9000, ctr: 5.0,
      cpc: 2.49, cpm: 124.4, conversions: 270, conversion_rate: 3.0,
      roas: 2.8, cpa: 83.0,
      updated_at: new Date().toISOString(),
    },
    ai_managed: true,
    optimization_frequency: "3hours",
    created_at: "2024-03-01T00:00:00Z",
    updated_at: new Date().toISOString(),
  },
  {
    id: "camp-7",
    client_id: "client-3",
    platform: "meta",
    platform_campaign_id: "23855501240",
    name: "Local Cafe Discovery",
    objective: "traffic",
    status: "active",
    daily_budget: 200,
    currency: "USD",
    start_date: "2024-05-01",
    targets: { roas: 6.0, cpa: 3 },
    metrics: {
      spend: 5800, impressions: 1200000, clicks: 72000, ctr: 6.0,
      cpc: 0.08, cpm: 4.8, conversions: 2880, conversion_rate: 4.0,
      roas: 6.2, cpa: 2.0, reach: 900000, frequency: 1.3,
      updated_at: new Date().toISOString(),
    },
    ai_managed: true,
    optimization_frequency: "6hours",
    created_at: "2024-05-01T00:00:00Z",
    updated_at: new Date().toISOString(),
  },
  {
    id: "camp-8",
    client_id: "client-1",
    platform: "meta",
    name: "Holiday Campaign - Draft",
    objective: "sales",
    status: "draft",
    daily_budget: 2000,
    currency: "USD",
    start_date: "2024-11-15",
    targets: { roas: 5.0, monthly_budget: 60000 },
    metrics: {
      spend: 0, impressions: 0, clicks: 0, ctr: 0,
      cpc: 0, cpm: 0, conversions: 0, conversion_rate: 0,
      roas: 0, cpa: 0,
      updated_at: new Date().toISOString(),
    },
    ai_managed: true,
    optimization_frequency: "1hour",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const MOCK_ASSETS: Asset[] = [
  {
    id: "asset-1", client_id: "client-1", type: "image", name: "Summer Hero Banner",
    url: "https://picsum.photos/seed/summer1/800/600",
    thumbnail_url: "https://picsum.photos/seed/summer1/400/300",
    width: 1200, height: 628, file_size: 284000, mime_type: "image/jpeg",
    tags: ["summer", "hero", "banner"], ai_generated: false,
    performance_score: 87, usage_count: 6, created_at: "2024-06-01T00:00:00Z",
  },
  {
    id: "asset-2", client_id: "client-1", type: "image", name: "Running Shoes Product",
    url: "https://picsum.photos/seed/shoes1/800/600",
    thumbnail_url: "https://picsum.photos/seed/shoes1/400/300",
    width: 1080, height: 1080, file_size: 196000, mime_type: "image/jpeg",
    tags: ["product", "shoes", "square"], ai_generated: false,
    performance_score: 92, usage_count: 11, created_at: "2024-05-15T00:00:00Z",
  },
  {
    id: "asset-3", client_id: "client-1", type: "video", name: "Brand Story 30s",
    thumbnail_url: "https://picsum.photos/seed/video1/400/300",
    width: 1920, height: 1080, duration: 30, file_size: 8400000, mime_type: "video/mp4",
    tags: ["brand", "video", "story"], ai_generated: false,
    performance_score: 78, usage_count: 4, created_at: "2024-06-10T00:00:00Z",
  },
  {
    id: "asset-4", client_id: "client-1", type: "copy",
    name: "Summer Sale Headline",
    content: "Run Faster. Live Bolder. Up to 40% Off Summer Collection — Shop Now.",
    tags: ["headline", "summer", "sale"], ai_generated: true,
    performance_score: 94, usage_count: 8, created_at: "2024-06-05T00:00:00Z",
  },
  {
    id: "asset-5", client_id: "client-1", type: "copy",
    name: "Retargeting Primary Text",
    content: "You left something behind! Your perfect pair is waiting — complete your order today and enjoy free shipping.",
    tags: ["retargeting", "cart", "urgency"], ai_generated: true,
    performance_score: 89, usage_count: 5, created_at: "2024-06-15T00:00:00Z",
  },
  {
    id: "asset-6", client_id: "client-1", type: "image", name: "Athlete Lifestyle Shot",
    url: "https://picsum.photos/seed/athlete1/800/600",
    thumbnail_url: "https://picsum.photos/seed/athlete1/400/300",
    width: 1200, height: 628, file_size: 312000, mime_type: "image/jpeg",
    tags: ["lifestyle", "athlete", "motion"], ai_generated: false,
    performance_score: 81, usage_count: 7, created_at: "2024-06-08T00:00:00Z",
  },
  {
    id: "asset-7", client_id: "client-1", type: "image", name: "Collection Grid 4-up",
    url: "https://picsum.photos/seed/grid1/800/600",
    thumbnail_url: "https://picsum.photos/seed/grid1/400/300",
    width: 1200, height: 1200, file_size: 420000, mime_type: "image/jpeg",
    tags: ["collection", "grid", "catalog"], ai_generated: false,
    performance_score: 73, usage_count: 3, created_at: "2024-06-20T00:00:00Z",
  },
  {
    id: "asset-8", client_id: "client-1", type: "copy",
    name: "PMax Description",
    content: "Discover Nike's latest running innovations. Advanced cushioning, lightweight materials, and iconic style for every type of runner.",
    tags: ["description", "pmax", "brand"], ai_generated: true,
    performance_score: 86, usage_count: 9, created_at: "2024-05-20T00:00:00Z",
  },
];

export const MOCK_AI_ACTIONS: AIAction[] = [
  {
    id: "action-1",
    client_id: "client-1",
    campaign_id: "camp-1",
    campaign_name: "Summer Collection - Awareness",
    platform: "meta",
    action_type: "budget_increase",
    title: "Increased daily budget by 20%",
    reasoning: "ROAS is 4.6x vs target of 4.0x. CTR has improved 0.8pts week-over-week with stable CPA. Scaling budget to capture additional high-intent audience during peak season.",
    details: { from: 1000, to: 1200, metric: "daily_budget", currency: "USD" },
    predicted_impact: "Estimated +$3,200 additional revenue at current ROAS",
    actual_impact: "+$3,840 additional revenue in 7 days",
    approval_status: "approved",
    approved_by: "Sarah Johnson",
    approved_at: "2024-07-10T09:15:00Z",
    executed_at: "2024-07-10T09:15:00Z",
    created_at: "2024-07-10T09:00:00Z",
  },
  {
    id: "action-2",
    client_id: "client-1",
    campaign_id: "camp-5",
    campaign_name: "Lookalike - High Value Customers",
    platform: "meta",
    action_type: "pause_ad",
    title: "Paused 3 underperforming ad creatives",
    reasoning: "3 creatives have CTR below 0.8% after 5,000+ impressions each with ROAS below 1.5x. Pausing to focus spend on top 2 performers with 3.2x+ ROAS.",
    details: { paused_ads: ["Ad_456", "Ad_789", "Ad_012"] },
    predicted_impact: "Improve campaign ROAS from 2.1x to 3.0x+",
    approval_status: "approved",
    approved_by: "Mike Chen",
    approved_at: "2024-07-12T14:30:00Z",
    executed_at: "2024-07-12T14:30:00Z",
    created_at: "2024-07-12T14:00:00Z",
  },
  {
    id: "action-3",
    client_id: "client-1",
    campaign_id: "camp-2",
    campaign_name: "Running Shoes - Performance Max",
    platform: "google",
    action_type: "bid_increase",
    title: "Raised target ROAS from 500% to 520%",
    reasoning: "Campaign has consistently beaten ROAS target for 14 days. Tightening target to improve efficiency while maintaining volume. Search impression share at 62% — room to be more selective.",
    details: { from: 500, to: 520, metric: "target_roas_percent" },
    predicted_impact: "Improve ROAS by ~0.1-0.2x with minimal volume loss",
    actual_impact: "ROAS improved to 5.2x, volume maintained within 3%",
    approval_status: "approved",
    approved_by: "Sarah Johnson",
    approved_at: "2024-07-08T11:00:00Z",
    executed_at: "2024-07-08T11:00:00Z",
    created_at: "2024-07-08T10:45:00Z",
  },
  {
    id: "action-4",
    client_id: "client-1",
    campaign_id: "camp-1",
    campaign_name: "Summer Collection - Awareness",
    platform: "meta",
    action_type: "asset_swap",
    title: "Swapped hero creative — replaced 2 low-CTR images",
    reasoning: "\"Summer Hero Banner\" (asset-1) shows 3.8% CTR vs. campaign average 2.4%. Replacing \"Old Catalog\" (0.7% CTR) and \"Static Product\" (0.9% CTR) with high-performer and AI-generated variants.",
    details: { removed: ["asset-old-1", "asset-old-2"], added: ["asset-1", "asset-4"] },
    predicted_impact: "Estimated CTR uplift from 2.4% to 3.2%, reducing CPM effective cost",
    approval_status: "pending",
    created_at: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: "action-5",
    client_id: "client-1",
    campaign_id: "camp-8",
    campaign_name: "Holiday Campaign - Draft",
    platform: "meta",
    action_type: "campaign_created",
    title: "Created Holiday Campaign draft for review",
    reasoning: "Based on last year's Q4 performance data and current asset pool, generated a full campaign structure: 3 ad sets (Prospecting 1%, Retargeting 30d, Cart Abandoners), 12 ads using top-performing assets. Budget allocation optimized for peak November 25 – December 25 period.",
    details: {
      ad_sets: 3, ads: 12, estimated_reach: "2.4M–4.1M",
      projected_roas: 5.2, projected_spend: 55000,
    },
    predicted_impact: "Projected $286,000 revenue at 5.2x ROAS based on historical data",
    approval_status: "pending",
    created_at: new Date(Date.now() - 7200000).toISOString(),
  },
  {
    id: "action-6",
    client_id: "client-1",
    campaign_id: "camp-3",
    campaign_name: "Brand Search - Core Terms",
    platform: "google",
    action_type: "update_targeting",
    title: "Added 14 new negative keywords",
    reasoning: "Search term report shows 18% of spend on irrelevant queries (competitor brand names, DIY terms). Adding negatives to prevent wasted spend. Estimated savings: $180/week.",
    details: { negative_keywords: ["free", "diy", "cheap", "review", "vs adidas"], count: 14 },
    predicted_impact: "Reduce wasted spend by ~$180/week, improve CPA by ~8%",
    actual_impact: "CPA improved from $8.1 to $7.3 in 10 days",
    approval_status: "approved",
    approved_by: "Mike Chen",
    approved_at: "2024-07-05T16:00:00Z",
    executed_at: "2024-07-05T16:00:00Z",
    created_at: "2024-07-05T15:45:00Z",
  },
];

export const MOCK_TEAM: TeamMember[] = [
  {
    id: "member-1", agency_id: "agency-1", user_id: "user-1",
    email: "sarah@agency.com", name: "Sarah Johnson", role: "admin",
    invited_at: "2024-01-01T00:00:00Z", joined_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "member-2", agency_id: "agency-1", user_id: "user-2",
    email: "mike@agency.com", name: "Mike Chen", role: "manager",
    invited_at: "2024-02-01T00:00:00Z", joined_at: "2024-02-02T00:00:00Z",
  },
  {
    id: "member-3", agency_id: "agency-1", user_id: "user-3",
    email: "priya@agency.com", name: "Priya Patel", role: "manager",
    invited_at: "2024-03-15T00:00:00Z", joined_at: "2024-03-16T00:00:00Z",
  },
  {
    id: "member-4", agency_id: "agency-1", user_id: "user-4",
    email: "james@agency.com", name: "James Wu", role: "viewer",
    invited_at: "2024-04-10T00:00:00Z", joined_at: "2024-04-11T00:00:00Z",
  },
];

export const MOCK_DASHBOARD_METRICS: DashboardMetrics = {
  total_spend: 62400,
  total_spend_change: 12.4,
  avg_roas: 4.2,
  avg_roas_change: 8.1,
  total_conversions: 7266,
  total_conversions_change: 15.3,
  active_campaigns: 8,
  active_campaigns_change: 1,
  pending_approvals: 2,
  ai_actions_today: 7,
  shopify_revenue: 284600,
  shopify_orders: 1842,
  shopify_revenue_change: 18.6,
};

export const MOCK_CHART_DATA: ChartDataPoint[] = [
  { date: "Jun 1", spend: 38200, roas: 3.8, conversions: 4200, clicks: 82000, shopify_revenue: 145200 },
  { date: "Jun 8", spend: 41000, roas: 4.0, conversions: 4600, clicks: 88000, shopify_revenue: 164000 },
  { date: "Jun 15", spend: 44500, roas: 4.1, conversions: 5100, clicks: 95000, shopify_revenue: 182400 },
  { date: "Jun 22", spend: 48200, roas: 4.3, conversions: 5800, clicks: 102000, shopify_revenue: 207300 },
  { date: "Jun 29", spend: 52000, roas: 4.0, conversions: 5400, clicks: 108000, shopify_revenue: 208000 },
  { date: "Jul 6", spend: 56800, roas: 4.2, conversions: 6200, clicks: 115000, shopify_revenue: 238560 },
  { date: "Jul 13", spend: 62400, roas: 4.2, conversions: 7266, clicks: 124000, shopify_revenue: 284600 },
];

export const MOCK_PLATFORM_SPLIT = [
  { platform: "Meta", spend: 38200, roas: 4.6, conversions: 5100, campaigns: 5 },
  { platform: "Google", spend: 24200, roas: 3.6, conversions: 2166, campaigns: 3 },
];
